### ISSUE TITLE
Speeding up the 'vsc list' command

### ISSUE THREAD

**Issue by raavann** [tusharsadhwani/vscvm#19]
So the code web scraps the recent versions whenever the `vsc list` command is run.. um.. if we maintain a .db(mysql lite 3) file that stores version info-s and gets updated once every day/week.. that could possibly speed up the `list` command..? cause then whenever the list command is run.. it would just return the data already stored in the db.?

**Comment by tusharsadhwani** [comment]
What would happen if a new version is released? How would it know?

**Comment by raavann** [comment]
updates are not released that frequently :!
you can increase the frequency to 5 minutes.. the idea is to speed up the list command not delay the update command..

**Comment by tusharsadhwani** [comment]
Well normally you would only check the list once a day or so. I'm not sure why I would want to cache the result

**Comment by raavann** [comment]
okay
